package v2d2.actions.knock

object Answers {
  val answers: List[String] = List(
    "Aardvark a hundred miles for one of your smiles!",
    "Aaron on the side of caution!",
    "Abbott time you answered the door!",
    "Abe C D E F G H...! ",
    "Abyssinia behind bars one of these days!",
    "Acid down and be quiet!",
    "Ada burger for lunch! ",
    "Adair once but I'm bald now!",
    "Adam if I do and adam if I don't! ",
    "Adelia the cards and we'll play snap!",
    "Adlai a bet on that!",
    "Adolf ball hit me in the mouth!",
    "Aesop I saw a puddy cat! ",
    "Agatha headache. Do you have an aspirin?",
    "Agnes & Topeka & the Santa Fe!",
    "Ahmedeus Motzart! ",
    "Alaska my friend the question then!",
    "Aida lot of sweets and now I've got tummy ache!",
    "Al give you a kiss if you open this door! ",
    "Aladdin the street wants a word with you!",
    "No thanks, but I'd like some peanuts!",
    "Doris locked that's why I am knocking!",
    "Ken I come in, it's freezing out here?",
    "Armageddon out of here!",
    "Howl you know unless you open the door!",
    "Aldo anywhere with you!",
    "Alec-tricity. Isn't that a shock!",
    "Alec my lolly!",
    "Alex the questions round here!",
    "Alexia again to open this door!",
    "Alfalfa you, if you give me a kiss!",
    "Alfie terrible if you leave!",
    "Alfred of the dark!",
    "Alfred the needle if you sew!",
    "Ali, Ali oxen free!",
    "I'm Alice chasing rainbows....!",
    "Alison it's dark outside!",
    "Allan-d of Manhattan!",
    "Allegra is broken! ",
    "Alligator, that's who!",
    "Allied, so sue me!",
    "Alma-ny Knock Knock jokes can you take!",
    "Alma not going to tell you!",
    "Almond the side of the law!",
    "Alpaca the trunk, you pack the suitcase!",
    "Althea later, alligator!",
    "Alva heart!",
    "Alvin a great time, how about you?",
    "Amahl shook up!",
    "Amana bad mood!",
    "Amazon of a gun!",
    "Amin thing to do!",
    "Ammonia little kid!",
    "Amory Christmas and a Happy New Year!",
    "Amosquito just bit me!",
    "Amy fraid I've forgotten!",
    "Andrew a picture!",
    "Andy mosquito bit me again!",
    "Anita you like I need a hole in the head!",
    "Anka the ship!",
    "Ankansas though any piece of wood!",
    "Ankara went off the cliff!",
    "Anndromeda Strain!",
    "Anna one, anna two...!",
    "Anna going to tell you!",
    "Anne Boleyn alley!",
    "Annetta wisecrack and you're out of here!",
    "Annie one you like!",
    "You Anthem devil you!",
    "Anthony you want!",
    "Apple your hair if you don't let me in!",
    "Arbus leaves in 5 minutes?",
    "You catching a cold?",
    "Aretha flowers!",
    "Argo down the shops!",
    "Aries a reason why I talk this way!",
    "Arizona room for one of us in this town!",
    "Armageddon getting out of here!",
    "Armenia every word I say!",
    "Arnie having fun?",
    "Arnold friend you haven't seen for years!",
    "Arthur any more biscuits in the tin!",
    "Asa-int amongst men!",
    "Ashley-t's foot!",
    "Asia you going to let me in then!",
    "Astor the ball is over!",
    "I'm sorry I didn't know you had a cold!",
    "Athena flying saucer!",
    "Athens I love you!",
    "Atlas it's the weekend!",
    "Atomic ache!",
    "Audrey be doing this!",
    "Augusta go home now!",
    "Aunt Lou do you think you are!",
    "Austin corrected!",
    "Avenue head the good news!",
    "Avocado a cold!",
    "Axeldental Tourist!",
    "Axl me nicely and I might just tell you!",
    "Bach of sweets!",
    "Bacon a cake for your birthday!",
    "Barbara black sheep, have you any wool...!",
    "Beatle Bailey!",
    "Bean fishing lately?",
    "Beethoven is too hot!",
    "Beets me!",
    "Bella bottom trousers!",
    "Ben knocking on this door all morning!",
    "Beezer black and yellow and make honey!",
    "Beirut force!",
    "Belize in yourself!",
    "Benin shopping lately?",
    "Bera necessity!",
    "Berlin the water for my hard boiled eggs!",
    "Bernadette ate all my dinner and now I'm starving!",
    "Bertha-day greetings!",
    "Beryl of beer!",
    "Betty-lou a few pounds!",
    "Betty ya don't know who this is!",
    "Betty-bye!",
    "Bibi gun!",
    "Bitter Bianca next train out of here, pardner!",
    "Bjorn Free!",
    "Bo Geste!",
    "Boliva me, I know what I'm talking about!",
    "Bologna & cheese!",
    "Bolton the door!",
    "Bolzano the door!",
    "Don't cry it's only a joke!",
    "Borg out of my mind!",
    "Brad news I'm afraid!",
    "Brewsters can wake you up in the morning singing cock-a-doodle doo!",
    "London Bridget, is falling down, falling down...!",
    "Brie me my supper!",
    "Drigham back my sunshine back to me...!",
    "Durns me up!",
    "Burton in the hand is worth two in the bush!",
    "Bush your money where your mouth is!",
    "Butch your arms around me!",
    "Butcher money where your mouth is!",
    "Butter bring an umbrella, it looks like it might rain!",
    "Button in is not polite!",
    "Cabotret!",
    "Camalot is where King Arthur lived!",
    "Candice get any better!",
    "Candy cow jump over the moon!",
    "Carl get you there quicker than if you walk!",
    "Carmen get it!",
    "Carrie the bags into the house please!",
    "Carrot me back home!",
    "Cash me if you can!",
    "I knew you were nuts!",
    "Cass more flies with honey than vinegar!",
    "Cassie the forest for the trees!",
    "Castorblanca!",
    "Castro bread upon the waters!",
    "Cathy the the doorbell, it's too dark out here!",
    "Cecil have music whereever she goes....!",
    "Cecile this envelope!",
    "Celery me you lunch will you, I'm hungry!",
    "Celeste time I'm going to tell you this!",
    "Cello dere!",
    "Cereal pleasure to meet you!",
    "Chad to make your acquaintance!",
    "Cheese a cute girl!",
    "Cher and share alike!",
    "Cherry oh, see you later!",
    "Chester the nick of time!",
    "Chesterfield my leg so I slapped him!",
    "Chicken the oven, I can smell burning!",
    "Chile out tonight!",
    "Chip of Fools!",
    "China just like old times isn't it!",
    "Chloe's Encounters of the Third Kind!",
    "Chopin the supermarket!",
    "Chow mein to meet you my dear!",
    "Chuck and see if the door is locked!",
    "Chuck in a sandwich for lunch!",
    "Cicero the boat ashore!",
    "Cigarette life if you don't weaken!",
    "Clara space on the table!",
    "Clare your throat before you speak!",
    "Clarence sale!",
    "Cliff the hedges!",
    "Colleen up this mess!",
    "Colin all cars, Colin all cars!",
    "Colin the doctor, I feel ill!",
    "Collier big brother see if I care!",
    "Cologne me names won't help!",
    "Coolidge a cucumber!",
    "Conga go on meeting like this!",
    "Congo out, I'm grounded!",
    "Conyers please open the door!",
    "Cuckoo yourself, I don't come here to be insulted!",
    "Costa lot!",
    "Cozy who's knocking!",
    "Cronkite evidence!",
    "Cugat to love my jokes!",
    "Curry me back home will you!",
    "Custer a penny to find out!",
    "Cynthia you been away I missed you!",
    "Cy'n on the botton line!",
    "Cyril nice to meet you!",
    "Daisy plays, nights he sleeps!",
    "Dali've me alone!",
    "Dana talk with your mouth full!",
    "Dale come if you ask dem!",
    "Darius a lot I have to tell you!",
    "Darren young man on the flying machine!",
    "I'll be Darwin you open the door!",
    "Daryl never be another you...!",
    "Datsun old joke!",
    "Dave for Night!",
    "Dawn leave me out here in the cold!",
    "Deanna-mals are restless open the cage!",
    "Donald Deduct!",
    "Deena hear me the first time!",
    "Delhicatessen!",
    "Delores is on the side of the good guys!",
    "De Niro I am to you, the more I like you!",
    "Denis anyone?",
    "Dennis says I need to have a tooth out!",
    "Denise are above your ankles!",
    "Denver the good old days!",
    "Desi'gnated hitter!",
    "Desiree a ray of sunshine in my life...!",
    "Detail-a phone operator!",
    "Dewey have to keep saying all these jokes!",
    "De Witt now or never!",
    "Diane to meet you!",
    "Diesel teach me to go knocking around on doors!",
    "Dill we meet again!",
    "Dimension it!",
    "Dimitri is where the burgers grow!",
    "Dinah shoot until you see the whites of their eyes!",
    "Dino the answer!",
    "Diploma to fix the leak!",
    "Disaster be my lucky day!",
    "Disguise the limit!",
    "Dishes a very bad joke!",
    "Disk is recorded message, please leave your message after the beep!",
    "You just said it!",
    "Don Patrol!",
    "Donatello'n me!",
    "Don Giovanni talk to me!",
    "Don Juan to go to school today!",
    "Donald come baby, cradle and all...!",
    "Donalette the bed bugs bite!",
    "Donkey Hotey!",
    "Donna sit under an apple tree with anyone but me...!",
    "Donna Mae-k you an offer you can't refuse!",
    "Donovan know your own name!",
    "Dora wood!",
    "Doris slammed on my finger. Ouch!",
    "Dotty way the cookie crumbles!",
    "Doug good deeds and you'll go to heaven!",
    "Doughnut open until Christmas!",
    "Douglas is broken!",
    "Dozen anyone ever answer the door!",
    "Dragon your feet again!",
    "Drucilla kid you!",
    "Duane the bath, I'm dwowning!",
    "Dummy a favour and go away!",
    "Dunce-ay another word!",
    "Dustin Hoffman welcome mat for you!",
    "Dwayne in Spain falls mainly on the plain...!",
    "Dwight way and the wrong way!",
    "Earl be glad to tell you when you open this door!",
    "Ears looking at you!",
    "E.C. Street!",
    "Eddie body home!",
    "Edith, it'll make you feel better!",
    "Edna the class!",
    "Edwin some, you lose some!",
    "Egbert no bacon please!",
    "Egg-citing to meet you!",
    "Egypt you when he sold you a broken door bell!",
    "Elaine of the freeway!",
    "Eileen over to tie up my shoes!",
    "Elektra circus!",
    "Elias a terrible thing!",
    "Elizabeth of knowledge is a dangerous thing!",
    "Elke Seltzer - Plop Plop Fizz!",
    "Eli, Eli O!",
    "Ella-vator. Doesn't that give you a lift!",
    "Ella Man-tary my dear Wartson!",
    "Ellen-eed is love!",
    "Elsie you around!",
    "Emil for the poor!",
    "Emma bit cold out here, can you let me in?",
    "Emmett your service!",
    "Enid some more pocket money!",
    "Enoch and Enoch but no one answers the door!",
    "Esau down the road!",
    "Ethan me out of house and home you are!",
    "Essen it fun to listen to these jokes!",
    "Esther anything I can do for you!",
    "Ether bunny!",
    "Ettaquette!",
    "Eugenie from the bottle who will grant me three wishes?",
    "Eunice boy, let me in!",
    "Euripedes clothes and I'll sue you!",
    "Europe'ning the door too slow, come on!",
    "Europe to no good!",
    "Come Eustace you are!",
    "Eva you're deaf or your doorbell isn't working!",
    "Evan and earth!",
    "Eyesore do like you!",
    "Ezra no hope for me!",
    "Falafel off my bike and cut my knee!",
    "Fanny body home!",
    "Farley the leader!",
    "Farrah 'nough!",
    "Fatso the matter with you!",
    "Felix-cited all over!",
    "Felix my ice cream, I'll lick his!",
    "Ferdie last time open this door!",
    "Ferrer'vrything there is a season!",
    "Fez me, that's who!",
    "Fiddlesticks (Feet'll stick) out if the blanket is too short!",
    "Figs the doorbell, it's broken!",
    "Fletcher self go!",
    "Fiona had something better to do do you think we'd be knocking on this door!",
    "Fiona lookout for Mum & Dad ",
    "Florida bathroom is wet!",
    "Fonda you!",
    "Forbes of Evil!",
    "Ford he's a jolly good fellow!",
    "Foster than a speeding bullet!",
    "Fozzie hundredth time let me in!",
    "France of the family!",
    "Frances hello!",
    "Francie that!",
    "Francis on the other side of the Channel!",
    "Franks and beans!",
    "Franz, Romans, Countryman...!",
    "Fred Badge of Courage!",
    "Frederick Express!",
    "Freddie or not here I come!",
    "Freighter open the door!",
    "Rudolf the Fresno reindeer...!",
    "Frida be!",
    "Fruit of the loom!",
    "Gabe it my all!",
    "Gable to leap buildings in a single bound!",
    "Gabor'n to shop!",
    "Galway, your annoying me!",
    "Gandhi cane!",
    "Germany people knocking on your door?",
    "Genoa any new jokes?",
    "Gerald washed up kid!",
    "Gertie laundry!",
    "Ghana dance!",
    "Ghent out of here!",
    "Gilda umpire!",
    "Gina you don't recognize me!",
    "Ginastera at the people!",
    "Ginny a kiss!",
    "Gino me, now open the door!",
    "Giovanni go to a movie!",
    "Gipper your best!",
    "Giuseppe my apology?",
    "Giza nice boy!",
    "Gladys it's my last joke!",
    "Gladys the weekend, aren't you!",
    "Glasgow to the movies!",
    "Godunov to eat!",
    "Goose see a doctor, you don't look well!",
    "Gopher broke!",
    "Gordie-rectly to jail, do not pass go, do not collect $200!",
    "Gorilla me some cheese on toast please!",
    "Gorky will unlock the door!",
    "Gracie for you!",
    "Grady of Expectations!",
    "Grammar crackers. Pretty crummy!",
    "Grant you a wish, what is it!",
    "Grapes suzette!",
    "Gravy Crockett!",
    "Gregs of Wrath!",
    "Greta job!",
    "You Greta on my nerves!",
    "Gretal long little doggie...!",
    "Guinea a break!",
    "Guinevere going to get together!",
    "Gus you don't want to play?!",
    "Guthrie three blind mice!",
    "Hacienda the story!",
    "Hagar, you with the stars in your eyes....!",
    "Haifa cake is better than none!",
    "Hair today, gone tomorrow!",
    "Haiti see a good thing go to waste!",
    "Hal about Eve!",
    "Haleyen Nation!",
    "Haliburt a kiss sweetheart!",
    "Halifax you if you fax me!",
    "Handel with care!",
    "Handsome chips through the keyhole and I'll tell you more!",
    "Hank you!",
    "Hannah partridge in a pear tree!",
    "Hanover your money!",
    "Hans off the table!",
    "Hardy ha ha!",
    "Harlow will you go!",
    "Harmon on your side!",
    "Harold are you!",
    "Harriet it up!",
    "Harry you been!",
    "Harry up and answer this door!",
    "Havanna a wonderful time wish you were here!",
    "Fine, until you knocked on the door!",
    "Haydn in this cupboard is boring!",
    "Heart who hear you, speak louder!",
    "Heaven seen you in ages!",
    "Heidi-clare war on you!",
    "Heifer cow is better than none!",
    "Helena hand basket!",
    "Henrietta toadstool but thought it was a mushroom!",
    "Hepburn and indigestion!",
    "Herman is handsome!",
    "Hiawatha very bad today!",
    "Hiram fine, how are you!",
    "I'll Hoffman, I'll puff and I'll blow your house down!",
    "Holland you going to make me wait out here!",
    "Hollis forgiven, come back home!",
    "Hollylujah!",
    "Homer-again!",
    "Hominy times are we going to go through this!",
    "Honda the spreading chesnut tree...!",
    "Hope you'll have me!",
    "Horatio to the end of the street",
    "Harry up and answer this door!",
    "Hot air pardner, how ya doin'?",
    "House you doing!",
    "Great, House boy you?",
    "Howard can it be to guess a Knock Knock joke?",
    "Howard like to be outside for a change?",
    "Howard Huges like a punch on the nose?",
    "Howell you have your pizza, plain or with extra ham?",
    "I'm fine, how are you!",
    "Hubie-ginning to see the light!",
    "Huey too much!",
    "Hugh made me love you!",
    "Hugo your way and I'll go mine!",
    "Bless you, and I'm right out of tissues!",
    "Hyman in the mood for dancin'...!",
    "Ice cream of Jeannie!",
    "Ice cream soda whole world will know what a nut you are!",
    "Ichabod night out, can I borrow an umbrella!",
    "Idaho, not Ida-who, can't you say it!",
    "Ida bought another knocker if I were you!",
    "Idaho'd the whole garden but I was tired!",
    "Iglesias idea I ever had!",
    "Igloo knew Suzie like I know Suzie...!",
    "Iguana hold you hand!",
    "Ike-n't stop laughing!",
    "Ilka-pone!",
    "Ilona Ranger!",
    "Ima girl who can't say no...!",
    "Imogen life without chocolate!",
    "Ina Claire day, you can see for miles!",
    "India night time I go to sleep!",
    "India good old summertime...!",
    "Indiana'ls of history you'll be famous!",
    "I look at you and I get week Indonesia!",
    "Iona a great train set!",
    "Iowa you a dollar!",
    "Iran over here to tell you this!",
    "Irene and Irene but still no one answers the door!",
    "Iris you were here!",
    "Irma big girl now!",
    "Isaac'ly who do think this is?",
    "Isaac coming out?",
    "Isabella out of order!",
    "Isabelle necessary on a bicycle?",
    "Isadore locked, I can't get in!",
    "Isaiah nothing till you open this door!",
    "Istvan to be alone!",
    "Italy be a big job!",
    "Ivan enormous snake in my pocket!",
    "Ivana be rich!",
    "Ivor good mind not to tell you now!",
    "Ivory strong like Tarzan!",
    "Izzy come, Izzy go!",
    "Jackdraft!",
    "Jagger'd edge!",
    "Jaguar nimble, Jaguar quick!",
    "Jaimie a game of chess!",
    "Jamaica mistake!",
    "James people play!",
    "Jan of Green Gables!",
    "Janet'or in a drum!",
    "Japan is too hot, ouch!",
    "Jaws truly!",
    "Jeanius - you just don't recognise it!",
    "Jennymen prefer blondes!",
    "Jerome where you want to!",
    "Jerrold friend, thats who!",
    "Jess me",
    "Jess one of those things!",
    "Jessica more than I thought!",
    "Jester minute I'm trying to find my keys!",
    "Jethro the boat and stop talking so much!",
    "Jewell know if you open the door!",
    "Jewell remember me once you open the door!",
    "Jilly out here, so let me in!",
    "Joan you remember me?",
    "Joan call us we'll call you!",
    "Joanna big kiss!",
    "Joanne tell!",
    "Joe Namath not on the door thats why I knocked!",
    "Joey to the centre of the Earth!",
    "Johann a beautiful smile!",
    "Johannes are cold!",
    "John with the Wind!",
    "John the Navy!",
    "Jose can you see...!",
    "Josette down!",
    "Juan to hear some more of these?",
    "Juan of these days, pow, right in the kisser!",
    "Junita nother burger?",
    "Juicy what I just saw!",
    "Julia want to come in!",
    "Julia want some milk and cookies!",
    "Julie you door unlocked?",
    "Juliet me in or not!",
    "Juno what time it is!",
    "Jupiter fly in my soup!",
    "Jussi fruit!",
    "Justice as I thought, no one home!",
    "Justin time for tea!",
    "Kansas the best way to buy tuna!",
    "Kareem of the crop!",
    "Katherincan Queen!",
    "Kay sera sera!",
    "Ken I come in or do I have to climb through a window!",
    "Kendall and Barbie go together!",
    "Kenneth little kids play with you!",
    "Kent you tell who it is?",
    "Kentucky too well, have a sore throat!",
    "Kenya guess who is it?",
    "Ketchup the tree again!",
    "Kevin we go out and play?!",
    "Khomeini old time for dinner!",
    "Kim too late!",
    "Kipper hands to yourself!",
    "Kit me quick!",
    "Kittyzen Kane!",
    "Koch in the act!",
    "Kristin the baby in church!",
    "Kurt & Conan down down on the last act!",
    "Kyoto jail, do not pass go, do not collect $200!",
    "Laos and found!",
    "Lauren order!",
    "Laverne of catastrophe!",
    "Leaf me alone!",
    "Lee'd on McDuff!",
    "Leland of the free and the home of the brave!",
    "Lemon me give you a kiss!",
    "Len us a fiver will you!",
    "Lena little closer and I'll tell you!",
    "Lenny in, I'm hungry!",
    "Leon'ly one for me!",
    "Leona'ly way to go!",
    "Les go for a swim!",
    "Lester over a new leaf!",
    "Lettuce in and I'll tell you!",
    "Lilac a trooper!",
    "Lillian the garden!",
    "Lily house on the prairie!",
    "Lima Bean working on the railroad....!",
    "Lime bean!",
    "Lincoln logs!",
    "Lion down on the job again!",
    "Lionel bite you if you put your head in its mouth!",
    "Lisa a new car from $199 down and $199 a month!",
    "Lisa you can do is let me in!",
    "Lisbon married eight times!",
    "Listz of ingredients!",
    "I didn't know you could yodel!",
    "Livia me alone!",
    "Llama Yankee Doodle Dandy...!",
    "Lloyd a donkey to water but you can't make it drink!",
    "Lodz of fun!",
    "Lois the man on the totem pole!",
    "Louis'n up!",
    "Louisiana boy friend split up!",
    "Lucerne some maths today!",
    "Lucinda in the sky with diamonds...!",
    "Lucretia from the Black Lagoon!",
    "Luigi board!",
    "Luke through the keyhole and you'll see!",
    "Luther the silver lining!",
    "Lyndon ear and I'll tell you!",
    "Madame foot is caught in the door!",
    "Mae be I'll tell you or Mae be I won't!",
    "Maine I come in now please!",
    "Major answer didn't I!",
    "Malcome you didn't do your homework!",
    "Mali Brown!",
    "Manitoba me hours to get out of here!",
    "Manuel be sorry if you don't open this door!",
    "Mao'th of babes!",
    "Mara mara on the wall....!",
    "Marcella is full of water and I'm drowning, help!",
    "Marcia glad I stopped by!",
    "Marcus a book in the Bible!",
    "Maria me, I love you!",
    "Marian money!",
    "Marie the one you love!",
    "Marietta whole cake!",
    "Marilyn is a state north of Virginia!",
    "Marion on a Sunday!",
    "Marion haste, repent at leisure!",
    "Marmalade me said the little chicken!",
    "Martha them up to the top of the hill and the marched them down again!",
    "Marvin I wonderful!",
    "Mary Christmas!",
    "Mata of life and death!",
    "Matthew is pinthing my foot!",
    "The Maura the merrier!",
    "Max no difference. Open the door!",
    "Maxine the wave dude!",
    "Maxwell call later if your not going to answer!",
    "Maybe its a friend at the door!",
    "Maya best friend?",
    "Maybelle doesn't ring either!",
    "Mecca me happy!",
    "Medellin where you don't belong!",
    "Meg up your mind!",
    "Melita chickadee!",
    "Meredith kind of Knock Knock jokes and I'm leaving!",
    "Mickey is lost so that's why I'm knocking!",
    "Midas well open the door!",
    "Mikey won't fit in this lock!",
    "Minerva-s wreck from all these questions!",
    "Miniature open the door, I'll tell you!",
    "Minneapolis a day keeps the doctor away!",
    "Minnie more!",
    "No not Minnie-who - Minnehaha!",
    "Minsk meat!",
    "Miracle on 34th Street!",
    "Mischa a lot!",
    "Missouri loves compnay!",
    "Mitzi door shut, you'll never know!",
    "Monkey won't fit that's why I knocked!",
    "Montana your hide if she finds out you ate all of the cookies!",
    "Moose you be so nosy!",
    "Morris another day!",
    "Morrison, the more sun tan!",
    "Mort to the point, who are you!",
    "Mortimor that meets the eye!",
    "Mozart is in museums!",
    "Missed her at the bus stop!",
    "Muffin the matter with me, how about you?",
    "Muffin grouchy first thing in the morning!",
    "Munich me sick with all these jokes!",
    "Myth you too!",
    "Nadia head!",
    "Nadya head if you understand what I'm saying!",
    "Nanswer me or I'll go away!",
    "Nana you business!",
    "Neal and pray!",
    "Nebraska girl for a date she might say yes!",
    "Nettie as a fruitcake!",
    "Nevada saw you look so bad, you should be bed!",
    "Noah don't know who you are either!",
    "Norma'lly I have my key!",
    "Norma Lee don't go round knocking on doors!",
    "Norway will I leave till you open this door!",
    "What's nuisance since yesterday!",
    "Nurse sense talking to you!",
    "Oates'ay can you see!",
    "Ocelot of questions don't you!",
    "Odette's a bad sign!",
    "Odessa hot match ne!",
    "Odysseus the last straw!",
    "Ogre take a flying leap!",
    "Ohio Silver!",
    "Okra Winfrey!",
    "Olaf you!",
    "Oldest Son shines bright on my old Kentucky home...!",
    "Olga way when I'm good and ready!",
    "Olive none of your lip!",
    "Olive you!",
    "Oliver troubles are over!",
    "Olivia but I lost the key!",
    "Olivier but I've lost my key!",
    "Ollie time you say that, I wish you would cut it out!",
    "Oman, you are cute!",
    "Omar goodness gracious, wrong door!",
    "Omega best man win!",
    "Omelet'in you kiss me!",
    "Ooze in charge round here!",
    "Opera-tunity, and you thought opportunity only knocked once!",
    "Orange you even going to open the door!",
    "Orange juice going to talk to me!",
    "Orson around again!",
    "Orson buggy is about your speed!",
    "Osborn today - it's my birthday!",
    "Oscar a silly question, get a silly answer!",
    "O'Shea that's a sad story!",
    "Oslo down, whats the hurry!",
    "Oswald my chewing gum!",
    "Oswego marching, marching home ...!",
    "Othello you thalked to me!",
    "Otis a sin to tell a lie!",
    "Ottawa know you're telling the truth?",
    "Owen you open this door, I'm going to give you such a roasting!",
    "Owl Aboard!",
    "Ozzie you later!",
    "Pablo your horn!",
    "Pammy the key, the door is locked!",
    "Paris the thought!",
    "Parton my French!",
    "Passion through and I thought I'd say hello!",
    "Pasture bedtime isn't it!",
    "Pat yourself on the back!",
    "Paul up a chair and I'll tell you!",
    "Paula up the door handle will you and let me in!",
    "Peas of the rock!",
    "Pears the party!",
    "Pecan somebody your own size!",
    "Peg your pardon, I've got the wrong door!",
    "Perth your lips and whistle!",
    "Peru your point!",
    "Pharaoh enough!",
    "Phineas thing happened on the way to the forum!",
    "Philip my glass will you please!",
    "Philippa will you, I need a bath!",
    "Phoebe too expensive for me!",
    "Phyllis in on the news!",
    "Ping Pong the witch is dead....!",
    "Pizza the pie!",
    "Plato fish and chips please!",
    "Plums me that we'll always be friends!",
    "Police open up the door!",
    "Possum peace pipe!",
    "Prussia cooker!",
    "Not me - I just got here!",
    "Pyjamas around me and hold me tight!",
    "Quacker another bad joke and I'm leaving!",
    "Quebec to the end of the line!",
    "Quiet Tina courtroom - monkey wants to speak!",
    "Rabbit up carefully, it's a present!",
    "Raleigh round the flag boys!",
    "Randy four minute mile!",
    "Rapunzel troubles in your old kit bag....!",
    "Raoul of law!",
    "Rather not!",
    "Rayders of the Lost Ark!",
    "Raymond me way to buy some sweets!",
    "Razor hands, this is a stick up!",
    "Reagan maniac!",
    "Red peppers. Isn't that a hot one!",
    "Rena this bell doesn't do any good!",
    "Rene the marathon!",
    "Row, Row, Rhoda boat...!",
    "Ringo round the roses!",
    "Rita novel!",
    "Roberts and burglars will rob you blind!",
    "Robin your house!",
    "Rocky bye baby on the tree top...!",
    "Roland Stone gathers no moss!",
    "Rome is where the heart is!",
    "Ron dinnertime, give me a call!",
    "Rona the mill!",
    "Rosa corn grow in a field!",
    "Rosina vase!",
    "Roxanne your head or something!",
    "Roxie horrow picture show!",
    "Rufus leaking and I'm getting wet!",
    "Russia though you meal and you'll be sick!",
    "Ruth of the matter is!",
    "Sabina a long time since I've seen you!",
    "Sacha fuss, just because I knocked on your door!",
    "Saddam and shut up!",
    "Sadie Pledge of Allegiance!",
    "Safari so good!",
    "Sally dance!",
    "Salmonenchanted evening!",
    "Sam day you'll recognise me!",
    "Sam & Janet evening, you will meet a stranger...!",
    "Sameul be famous one day!",
    "Samuel sure is stubborn!",
    "Sandy door, I just got a splinter!",
    "Sara 'nother way in?!",
    "Sarah doctor in the house?",
    "Saturnday Night Fever!",
    "Saul the King's horses and all the King's men...!",
    "Savannah you going to open this door!",
    "Says me, that's who!",
    "Schachter Ripper. Feel like cutting up?",
    "Schatzi way the ball bounces!",
    "Schubert I can!",
    "Scissor and Cleopatra!",
    "Scold outside!",
    "Scott to be the morning after!",
    "Sebastion of the community!",
    "Senior so nosy, I'm not going to tell you!",
    "Seoul food!",
    "Seville you play with me?!",
    "Seymour if you open the door!",
    "Sharon share alike!",
    "Sheila be coming round the mountains when she comes...!!",
    "Shelby comin' round the mountain when she comes..!",
    "Shelly Cohn carne!",
    "Sherbert forest is where Robin Hood lived!",
    "Sherry your lunch and I'll be your best friend!",
    "Sherry dance?",
    "Sherwood like to come in!",
    "Shirley you must know me by now!",
    "Sicily question!",
    "Sid down and have a cup of tea!",
    "Simon the dotted line!",
    "Sinatra be a law!",
    "Sinbad and you'll never get to heaven!",
    "Sizzle hurt me more than it will hurt you!",
    "Soda you!",
    "Sofia me, I'm hungry!",
    "Sonata such a big deal!",
    "Sondheim soon!",
    "Sonia be another year older!",
    "Sophia the cat before dinner!",
    "Sonia paper moon...!",
    "Superman!",
    "Snow use, I've forgotten my key again!",
    "Spain to have to keep knocking on this door!",
    "Spider what everyone says. I like you!",
    "Spillane that Knock Knock joke!",
    "Spock louder!",
    "Stacey'ted until the bus stops!",
    "Stalin for time!",
    "Stan back or I'll shoot!",
    "Stanton here answering questions is no fun!",
    "STATUE! This is me.",
    "Stefan it quick before it bites me!",
    "Stella want to go home!",
    "One stepfather and I'll let you have it!",
    "Stevie on?",
    "Stopwatch your doing right now!",
    "Stu late to ask questions!",
    "Sue whomever you want!",
    "Sultan pepper!",
    "Summertime you can be a big pest!",
    "Sven Brides for Seven Brothers!",
    "Swede smell of success!",
    "Sweden the coffee!",
    "Sweden sour is my favourite chinese meal!",
    "Sycho!",
    "Sybil Simon met a pieman...!",
    "Tad's all folks!",
    "Taipei sixty words a minute is pretty fast!",
    "Tamara the world!",
    "Your welcome!",
    "Tarzan stripes forever!",
    "Teachers for the red white and blue. Hip hip..!",
    "Teheran up the road!",
    "Tennessee is played at Wimbledon!",
    "Tennis five plus five!",
    "Teresa green!",
    "Tex two to tango!",
    "Texas are getting higher every year!",
    "To be or not to be, thaddeus the question!",
    "Thatcher could get away with it!",
    "Thayer sorry and I won't tell teacher!",
    "Thea later, alligator!",
    "Thelma your soul!",
    "Thelonius kid in town!",
    "Theodore is shut, please open it!",
    "Theresa fly in my soup!",
    "Therese many a slip twixt the cup and the lip!",
    "Thermos be a better way!",
    "Therinheit or Centigrade, I always get mixed up!",
    "Thomas happy fella!",
    "Thumb like it hot and thumb like it cold!",
    "Thumping green and slimy is climbing up your back!",
    "Thurston and hungerin'!",
    "Early Tibet and early to rise!",
    "Tinker Bell is out of order!",
    "Toast where the days!",
    "Toby or not toby, that is the question!",
    "Tolkiens get you on the subway!",
    "Tom Sawyer underwear!",
    "Toothy the day after Monday!",
    "Torch you'd never ask!",
    "Toronto be a law against Knock Knock jokes!",
    "Toucan play at this game!",
    "Toyata be a law against such awful jokes!",
    "Tripoli play!",
    "Tsongas you're here, lets tell some Knock Knock jokes!",
    "Tuna piano and it'll sound better!",
    "Tunis company, three's a crowd!",
    "Turin to a vampire on Halloween!",
    "Turkey, open door!",
    "Turnip the heat it's cold in here!",
    "Twig or tweat!",
    "Twyla light of the Gods!",
    "Typhoid that song before!",
    "Tyrone shoelaces!",
    "Tyson of this on for size!",
    "Uganda get away with this!",
    "Keep Uriah on the ball!",
    "You go Uruguay and I'll go mine!",
    "Incorrect human it's: to whom.",
    "Never mind.  It's pointless",
    ".com",
    "R2-D2",
    "Sorry, 'who' is not a git command - did you mean 'show'?",
    "Mona Add!"
  )
}
